name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variants:
          - tag: ""
            label: "Default"
          - tag: "-fips"
            patches: fips.patch
            label: "FIPS"
            build_args: |
              BUILD_IMAGE=ghcr.io/goauthentik/fips-debian:trixie-slim-fips
    name: Build ${{ matrix.variants.label }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - id: tag
        run: |
          owner="${{ github.repository_owner }}"
          echo "org=$(echo $owner | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Apply patches
        run: |
          git apply ${{ matrix.variants.patches }} --allow-empty
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ghcr.io/${{ steps.tag.outputs.org }}/guacd
          flavor: |
            latest=auto
            suffix=${{ matrix.variants.tag }}
      - id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: ${{ matrix.variants.build_args }}
          file: Dockerfile.debian
          provenance: mode=max
          sbom: true
          cache-from: type=registry,ref=ghcr.io/${{ steps.tag.outputs.org }}/guacd:buildcache${{ matrix.variants.tag }}
          cache-to: type=registry,ref=ghcr.io/${{ steps.tag.outputs.org }}/guacd:buildcache${{ matrix.variants.tag }},mode=max
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-name: ghcr.io/${{ steps.tag.outputs.org }}/guacd
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: ${{ github.event_name != 'pull_request' }}
